import { GoogleGenAI, Modality } from "@google/genai";

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function summarizePdfText(text: string): Promise<string> {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Please summarize the following document text to create a concise version. The goal is to significantly reduce the word count while preserving the key information, arguments, and conclusions. Do not add any prefacing text like "Here is the summary". Just provide the summarized text directly.

      DOCUMENT TEXT:
      ---
      ${text}
      ---
      `,
    });
    return response.text;
  } catch (error) {
    console.error("Error summarizing text with Gemini:", error);
    throw new Error("Failed to get summary from AI. Please check your API key and network connection.");
  }
}

export async function editImageWithText(base64Data: string, mimeType: string, prompt: string): Promise<string> {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    
    throw new Error("No image was generated by the AI.");

  } catch (error) {
    console.error("Error editing image with Gemini:", error);
    throw new Error("Failed to edit image with AI. Please try again.");
  }
}
